### ISSUE TITLE
ETH Data file cutting off?

### ISSUE THREAD

**Issue by victoreram** [Nerolation/mevboost.pics#3]
Hey, when I load the parquet data on mevboost.pics, it cuts off at 2023-10-18.
```
import pandas as pd
df_eth_data = pd.read_parquet("openethdata_eth_data.parquet.gzip")
df_eth_data = df_eth_data.sort_values('block_number', ascending=False)
print(df_eth_data.head(3))
>                      date  block_number
> 1885501 2023-10-18 01:12:35    18373887.0
> 910279  2023-10-18 01:12:23    18373886.0
> 5504    2023-10-18 01:12:11    18373885.0
```
Here's the package versions I'm using:
```
versions:
pyarrow.__version__
'16.1.0'
pd.__version__
'1.4.1'
```
Not sure if the pubkey mapping is similarly affected since it doesn't have a timestamp. Anyone else seeing this?

**Comment by nerolation** [comment]
Yeah, this is a known issue. I'm running into size limits on my Google cloud backend. Will try to fix it asap

**Comment by nerolation** [comment]
@victoreram should be fixed now. Will wait for your confirmation (max 10 days) before closing.
Thanks for the heads up.

**Comment by victoreram** [comment]
@nerolation  Just checked, I see a min/max timestamp of 2024-01-22 15:49:35 and 2024-08-18 18:11:35 respectively

**Comment by victoreram** [comment]
@nerolation is it possible to get the timeseries from merge to ~current? If it's a limitation on storage on your end, I may be able to help

**Comment by nerolation** [comment]
Yeah it's currently a limit on the google cloud side. I would have to drop columns to get it done, thus decided to just export the reecent year.
Changing that should be easy but I'm not sure if I have the bandwidth for it (in the next couple of weeks).
Sorry for that.
